CREATE DATABASE CRUD

USE CRUD
GO 

CREATE TABLE Clientes (
	ClienteId INT IDENTITY (1,1),
	Nome VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL, 
	Sexo VARCHAR(10) NOT NULL,
	Endereco VARCHAR(50) NULL,
	Bairro VARCHAR(30) NULL,
	Telefone CHAR(9) NULL,
	Email VARCHAR(30) NULL
	CONSTRAINT ClienteId_PK PRIMARY KEY (ClienteId)
)

CREATE TABLE Produtos(
	ProdutoId INT IDENTITY (1,1),
	Nome VARCHAR(30),
	Descricao VARCHAR(50),
	Preco DECIMAL(10,2) ,
	Tipo VARCHAR(10),
	CONSTRAINT ProdutoId_PK PRIMARY KEY (ProdutoId)
)

CREATE TABLE ProdCli(
	ProdCliId INT IDENTITY(1,1),
	ClienteId INT,
	ProdutoId INT,
	CONSTRAINT ProdCli_PK PRIMARY KEY(ProdCliId),
	CONSTRAINT Cliente_FK FOREIGN KEY (ClienteId) REFERENCES Clientes (ClienteId),
	CONSTRAINT Produto_PK FOREIGN KEY (ProdutoId) REFERENCES Produtos (ProdutoId)
)

SELECT * FROM CLIENTES
SELECT * FROM PRODUTOS
SELECT * FROM PRODCLI
